baseline:
  name: GFS
  url: https://noaa-gfs-bdp-pds.s3.amazonaws.com/gfs.{{ yyyymmdd }}/{{ hh }}/atmos/gfs.t{{ hh }}z.pgrb2.0p25.f{{ "%03d" % fh }}
cycles:
  start: 2022-01-05T00:00:00
  step: 0
  stop: 2022-01-05T00:00:00
forecast:
  coords:
    latitude: latitude
    level: level
    longitude: longitude
    time:
      inittime: forecast_reference_time
      validtime: time
  name: anemoi_results
  path: ../postprocess/postprocessed_files/global.{{ yyyymmdd[:4] }}-{{ yyyymmdd[4:6] }}-{{ yyyymmdd[6:8] }}T{{ hh }}.48h.nc
  projection:
    proj: latlon
leadtimes:
  start: "00:00:00"
  step: "06:00:00"
  stop: "48:00:00"
meta:
  grids: "{{ meta.workdir }}/grids"
  levels: &levels [925]
  workdir: /content/AMS-2026-short-course/config/verification
paths:
  grids:
    baseline: "{{ meta.grids }}/baseline"
    forecast: "{{ meta.grids }}/forecast"
    truth: "{{ meta.grids }}/truth"
  obs: "{{ meta.workdir }}/obs"
  run: "{{ meta.workdir }}/run"
truth:
  name: PREPBUFR
  type: point
  url: https://noaa-reanalyses-pds.s3.amazonaws.com/observations/reanalysis/conv/prepbufr/{{ yyyymmdd[:4] }}/{{ yyyymmdd[4:6] }}/prepbufr/gdas.{{ yyyymmdd }}.t{{ hh }}z.prepbufr.nr
variables:
  tmp2m:
    level_type: heightAboveGround
    levels: [2]
    name: 2t
  spfh:
    level_type: isobaricInhPa
    levels: *levels
    name: q
  tmp:
    level_type: isobaricInhPa
    levels: *levels
    name: t
  ugrd:
    level_type: isobaricInhPa
    levels: *levels
    name: u
  vgrd:
    level_type: isobaricInhPa
    levels: *levels
    name: v
